workflows:
  version: 2
  test:
    jobs:
      - test
version: 2
jobs:
  test:
    environment:
      FLM_ENV: "test"
    docker:
      - image: circleci/python:3-stretch-node-browsers
    steps:
      - run:
          name: Verify python versions
          command: |
            python3 --version
            pip --version
      - run: sudo apt install gnupg2 python3-pyqt5 tor
      - run:
          name: Restart tor service
          command: sudo service tor restart
      - checkout
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -q --upgrade pip
            pip install -r ./requirements.txt
            pip install -r ./requirements-tests.txt
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python setup.py pytest
